server:
  port: 8080
spring:
  application:
    name: gulimall
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gulimall
      username: root
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#      supportBigNumbers: ture
#      bigNumberStrings: true


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

